CREATE DATABASE RETAIL_STORE
CREATE TABLE Products (
    ProductID INT,
    ProductName VARCHAR(100),
    Category VARCHAR(50),
    Price DECIMAL(10,2)
);
INSERT INTO Products VALUES(1,'LAPTOP','ELECTRONICS',40000),(2,'TELEVISION','ELECTRONICS',20000),
(3,'WASHING MACHINE','ELECTRONICS',20000),(4,'SHIRT','CLOTHING',1000),(5,'PANT','CLOTHING',900),
(6,'TSHIRTS','CLOTHING',900),(7,'BAT','Sports',1000),(8,'Ball','Sports',200)
INSERT INTO Products values(8,'glove','Sports',200),(9,'Track Pants','CLOTHING',500)

SELECT * FROM Products

//ROWNUMBER
SELECT P.*,
       ROW_NUMBER() OVER (PARTITION BY Category ORDER BY Price DESC) AS RowNum
FROM Products P;

//RANKNUMBER
SELECT P.*,
RANK() OVER(PARTITION BY Category ORDER BY Price DESC) as RNK
FROM Products P

//DENSERANK
SELECT P.*,
DENSE_RANK() OVER(PARTITION BY Category ORDER BY Price DESC) as D_RNK
FROM Products P

/*FILTER TOP 3 IN EACH CATEGORY*/
//Rownumber
SELECT * FROM(
SELECT P.*,
       ROW_NUMBER() OVER (PARTITION BY Category ORDER BY Price DESC) AS RowNum
FROM Products P) X
WHERE X.RowNum<=3

//Ranknumber
SELECT * FROM(
SELECT P.*,
RANK() OVER(PARTITION BY Category ORDER BY Price DESC) as RNK
FROM Products P) X
WHERE X.RNK<=3

//DENSERANK

SELECT * FROM(
SELECT P.*,
DENSE_RANK() OVER(PARTITION BY Category ORDER BY Price DESC) as DRNK
FROM Products P) X
WHERE X.DRNK<=3
